### ISSUE TITLE
Config files : Gather roles in ["roles"]

### ISSUE THREAD

**Issue by adrienluitot** [s0lst1ce/Botanist#97]
**Describe the bug**
I think it would be better to gather all the roles into the same array "roles".

**Comment by s0lst1ce** [comment]
I'm thinking this might be a bad idea since the `roles` array actually represents the clearances and `free_roles` doesn't fall in this category. Aside from a syntactic point of view it would also require me to change the `MendatoryConfig` in `config.py` for I wrote it so that we could add more clearances later on.
Maybe the best solution would be to rename `roles` to `clearance`?

**Comment by adrienluitot** [comment]
Yep this might be a solution too :D

**Comment by s0lst1ce** [comment]
Going for it then, expect it to be in effect with the next release (merge of `dev`).
